// Generated by CoffeeScript 1.3.3
(function() {
  var restful_sync;

  window.App = {
    Models: {},
    Collections: {},
    Views: {}
  };

  App.Events = _.extend({}, Backbone.Events);

  restful_sync = Backbone.sync;

  Backbone.sync = function(method, model, options) {
    var error, success;
    error = function(response) {
      return console.log("GLOBAL error");
    };
    success = function(response) {
      return console.log("GLOBAL success");
    };
    return restful_sync(method, model, options);
  };

}).call(this);
