// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Views.SchedulePage = (function(_super) {

    __extends(SchedulePage, _super);

    function SchedulePage() {
      return SchedulePage.__super__.constructor.apply(this, arguments);
    }

    SchedulePage.prototype.el = '#content';

    SchedulePage.prototype.initialize = function(options) {
      this.visits = new App.Collections.VisitList(options['unconfirmed']);
      this.visitListView = new App.Views.VisitListView({
        collection: this.visits
      });
      this.calendarView = new App.Views.CalendarView({
        collection: new App.Collections.VisitList()
      });
      return this.visitEditPane = new App.Views.VisitEditPane();
    };

    SchedulePage.prototype.render = function() {
      this.visitListView.render();
      this.calendarView.render();
      this.visitEditPane.render();
      return this;
    };

    return SchedulePage;

  })(Backbone.View);

}).call(this);
