// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Views.VisitDetailView = (function(_super) {

    __extends(VisitDetailView, _super);

    function VisitDetailView() {
      return VisitDetailView.__super__.constructor.apply(this, arguments);
    }

    VisitDetailView.prototype.tagName = 'li';

    VisitDetailView.prototype.className = 'visit-view';

    VisitDetailView.prototype.events = {
      "click": "updateEditPane"
    };

    VisitDetailView.prototype.initialize = function() {
      this.template = Handlebars.compile($('#tmpl-visit').html());
      this.model.on('change', this.render, this);
      return this.$el.attr('data-cid', this.model.cid);
    };

    VisitDetailView.prototype.updateEditPane = function(e) {
      App.Events.trigger('visit:selected', this.model);
      $(".visit-view").css({
        "background-color": "#ffffff"
      });
      return this.$el.css({
        "background-color": "#6F93DB"
      });
    };

    VisitDetailView.prototype.render = function() {
      return this.$el.html(this.template(this.model.toJSON()));
    };

    return VisitDetailView;

  })(Backbone.View);

}).call(this);
